[package]
name = "Pyth"
version = "0.0.2"
published-at = "0x04e20ddf36af412a4096f9014f4a565af9e812db9a05cc40254846cf6ed0ad91"

[dependencies.Wormhole]
git = "https://github.com/Typus-Lab/wormhole.git"
subdir = "sui/wormhole"
rev = "sui/mainnet"

[addresses]
pyth = "0x8d97f1cd6ac663735be08d1d2b6d02a159e711586461306ce60a2b7a6a565a9e"
